services:
  mysqlhost:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "authdb"
    volumes:
      - DatabaseVol:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/:ro
    expose:
      - 3306
      - 33060
  app:
    depends_on: 
      - mysqlhost
    image: graves869/fullstack-nginx-node:latest
    container_name: fullstack_app
    ports:
      - "80:80"
      - "443:443"
    restart: always
volumes:
  DatabaseVol:
